import repos from Archlinux
date: 20220601
svn-packages:  f62798c07054fe83e6e9480f7f9730cab757fed7
svn-community: e5b80414e236d496710af3f198da8961a866ea67

diff --git a/community/mdcat/PKGBUILD b/community/mdcat/PKGBUILD
--- a/community/mdcat/PKGBUILD
+++ b/community/mdcat/PKGBUILD
@@ -2,33 +2,39 @@
 # Maintainer: Justin Kromlinger <hashworks@archlinux.org>
 # Contributor: Wesley Moore <wes@wezm.net>
 pkgname=mdcat
-pkgver=0.25.0
+pkgver=0.27.1
 pkgrel=1
 pkgdesc='Sophisticated Markdown rendering for the terminal'
 arch=('i686' 'loongarch64' 'x86_64')
-url="https://github.com/lunaryorn/mdcat"
+url="https://codeberg.org/flausch/mdcat"
 license=('MPL2')
 options=(!lto)
-depends=('gcc-libs' 'openssl')
-makedepends=('cargo' 'asciidoctor')
-optdepends=('librsvg: used to render SVG images in kitty')
+depends=('gcc-libs'
+         'shared-mime-info')
+makedepends=('asciidoctor'
+             'cargo')
+optdepends=('less: for mdless'
+            'librsvg: used to render SVG images in kitty')
 source=("$pkgname-$pkgver.tar.gz::$url/archive/$pkgname-$pkgver.tar.gz")
-sha256sums=('92fddabab24f2e7d673b06c1f31a7746abbb547c5581faaed17a8e3e1e5b17a5')
+sha256sums=('79961e0a842ee0f68aee3d54b39458352664c67388e56175a9d18d80f357bf14')
+
+prepare() {
+  cd "$pkgname"
+  cargo fetch --locked --target "$CARCH-unknown-linux-gnu"
+}
 
 build() {
-  cd "$pkgname-$pkgname-$pkgver"
-  rustc --version
-  cargo --version
-  cargo build --release --locked --target-dir=target
+  cd "$pkgname"
+  cargo build --frozen --release --target-dir=target
 }
 
 check() {
-  cd "$pkgname-$pkgname-$pkgver"
-  cargo test --release --locked
+  cd "$pkgname"
+  cargo test --frozen
 }
 
 package() {
-  cd "$pkgname-$pkgname-$pkgver"
+  cd "$pkgname"
 
   install -Dm755 "target/release/$pkgname" "$pkgdir/usr/bin/$pkgname"
   # Hard link binary as mdless. When invoked as mdless mdcat will paginate
@@ -37,21 +43,17 @@ package() {
 
   # Required until https://github.com/rust-lang/cargo/issues/6790
   # Should never fail with extra-x86_64-build
-  COMPLETIONS_DIR="$(find target/release/build -type d -path "target/release/build/mdcat-*/out/completions")"
-  if [ ! "$(echo "$COMPLETIONS_DIR" | wc -l)" -eq 1 ]; then
-    >&2 echo "Error: Unexpected count of completions dirs"
+  OUT_DIR="$(find target/release/build -type d -path "target/release/build/mdcat-*/out")"
+  if [ ! "$(echo "$OUT_DIR" | wc -l)" -eq 1 ]; then
+    >&2 echo "Error: Unexpected count of out dirs"
     return 1
   fi
 
-  install -Dm644 "$COMPLETIONS_DIR/_mdcat" \
-    "$pkgdir/usr/share/zsh/site-functions/_mdcat"
-  install -Dm644 "$COMPLETIONS_DIR/mdcat.bash" \
-    "$pkgdir/usr/share/bash-completion/completions/mdcat"
-  install -Dm644 "$COMPLETIONS_DIR/mdcat.fish" \
-    "$pkgdir/usr/share/fish/vendor_completions.d/mdcat.fish"
+  install -Dm644 "$OUT_DIR/_mdcat" "$pkgdir/usr/share/zsh/site-functions/_mdcat"
+  install -Dm644 "$OUT_DIR/mdcat.bash" "$pkgdir/usr/share/bash-completion/completions/mdcat"
+  install -Dm644 "$OUT_DIR/mdcat.fish" "$pkgdir/usr/share/fish/vendor_completions.d/mdcat.fish"
 
-  MANPAGE="$COMPLETIONS_DIR/../mdcat.1"
+  MANPAGE="$OUT_DIR/mdcat.1"
   gzip -n "$MANPAGE"
-  install -Dm 644 "$MANPAGE.gz" \
-    "$pkgdir/usr/share/man/man1/mdcat.1.gz"
+  install -Dm644 "$MANPAGE.gz" "$pkgdir/usr/share/man/man1/mdcat.1.gz"
 }
