import repos from Archlinux
date: 20210701
svn-packages:  dd462ee30cd85349d93fd2ea747d54b992361398
svn-community: e077215dcce01b21997452298f85d236f572e638

diff --git a/community/haskell-doctest/PKGBUILD b/community/haskell-doctest/PKGBUILD
--- a/community/haskell-doctest/PKGBUILD
+++ b/community/haskell-doctest/PKGBUILD
@@ -3,18 +3,19 @@
 
 _hkgname=doctest
 pkgname=haskell-doctest
-pkgver=0.17
-pkgrel=22
+pkgver=0.18.1
+pkgrel=37
 pkgdesc="Test interactive Haskell examples"
 url="https://github.com/sol/doctest"
 license=("MIT")
 arch=('loongarch64' 'x86_64')
-depends=('ghc-libs' 'haskell-base-compat' 'haskell-ghc' 'haskell-syb' 'haskell-code-page'
-         'haskell-ghc-paths')
-makedepends=('ghc' 'haskell-hunit' 'haskell-hspec' 'haskell-hspec-core' 'haskell-quickcheck'
-             'haskell-stringbuilder' 'haskell-silently' 'haskell-setenv' 'haskell-mockery')
+depends=('ghc-libs' 'haskell-base-compat' 'haskell-exceptions' 'haskell-ghc' 'haskell-syb'
+         'haskell-code-page' 'haskell-ghc-paths')
+makedepends=('ghc')
+checkdepends=('haskell-hunit' 'haskell-hspec' 'haskell-hspec-core' 'haskell-quickcheck'
+              'haskell-stringbuilder' 'haskell-silently' 'haskell-setenv' 'haskell-mockery')
 source=("https://hackage.haskell.org/packages/archive/${_hkgname}/${pkgver}/${_hkgname}-${pkgver}.tar.gz")
-sha512sums=('7816af9e0ca419a0837b8a8c3bc943edbc44ec73d2a36acd8a7e868d370db9f60557667aa8efb81444aad47860defa6374b496fdcbd8f80403ee74e8b2543cee')
+sha512sums=('e9e74eed4246f3aeaa71940db8275f080be0a5e296c43b16b48228dbafac821643572edca3210a65d315ebbe900a1c484346aee75c88add052d9640ff008fc82')
 
 prepare() {
     # Add -dynamic flag
@@ -25,8 +26,14 @@ prepare() {
 build() {
     cd $_hkgname-$pkgver
 
+    if (( CHECKFUNC )); then
+        _opts=('--enable-tests')
+    else
+        _opts=('--disable-tests')
+    fi
+
     runhaskell Setup configure -O --enable-shared --enable-executable-dynamic --disable-library-vanilla \
-        --prefix=/usr --docdir=/usr/share/doc/$pkgname --enable-tests \
+        --prefix=/usr --docdir=/usr/share/doc/$pkgname "${_opts[@]}" \
         --dynlibdir=/usr/lib --libsubdir=\$compiler/site-local/\$pkgid
     runhaskell Setup build $MAKEFLAGS
     runhaskell Setup register --gen-script
@@ -37,7 +44,7 @@ build() {
 
 check() {
     cd $_hkgname-$pkgver
-    runhaskell Setup test || warning "Tests failed"
+    runhaskell Setup test || echo "Tests failed"
 }
 
 package() {
diff --git a/community/pifpaf/PKGBUILD b/community/pifpaf/PKGBUILD
--- a/community/pifpaf/PKGBUILD
+++ b/community/pifpaf/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: Felix Yan <felixonmars@archlinux.org>
 
 pkgname=pifpaf
-pkgver=3.0.0
+pkgver=3.1.5
 pkgrel=1
 pkgdesc='Suite of tools and fixtures to manage daemons for testing'
 arch=('any')
@@ -15,12 +15,16 @@ replaces=('python-pifpaf')
 makedepends=('python-setuptools')
 checkdepends=('python-testrepository' 'python-requests' 'python-testtools' 'python-oslotest'
               'memcached' 'percona-server' 'percona-server-clients' 'postgresql' 'redis'
-              'ceph' 'consul' 'couchdb' 'httpbin' 'rabbitmq')
-# 'elasticsearch': test fails
-source=("$pkgname-$pkgver.tar.gz::https://github.com/jd/pifpaf/archive/$pkgver.tar.gz")
-sha512sums=('78d5daae08e6c5ee664619ca7683c04379502c6f667ff9ca7dd07e4dee798c1ec7c8adafb48bddcc8ba33dd0e6b09790da2f6e6d7181468450d800186faa41f4')
+              'ceph' 'consul' 'couchdb' 'elasticsearch' 'httpbin' 'rabbitmq')
+source=("https://github.com/jd/pifpaf/archive/$pkgver/$pkgname-$pkgver.tar.gz")
+sha512sums=('075340303f17aa0067c1bc19ca861255efffb6c64f353f7334fa069dfc4456f067aa487ecfa45bb48291e3d9d949f801cead95f6e833d85086090f6c2fdef349')
 
 export PBR_VERSION=$pkgver
+
+prepare() {
+  cd pifpaf-$pkgver
+  echo "graft pifpaf/drivers/templates" > MANIFEST.in
+}
 
 build() {
   cd pifpaf-$pkgver
@@ -32,7 +36,8 @@ check() {
 
   cd pifpaf-$pkgver
   python setup.py install --root="$PWD/tmp_install" --optimize=1
-  PYTHONPATH="$PWD/tmp_install/usr/lib/python3.8/site-packages" PATH="$PWD/tmp_install/usr/bin:$PATH" python setup.py testr
+  # TODO: fix test failures
+  PYTHONPATH="$PWD/tmp_install/usr/lib/python3.9/site-packages" PATH="$PWD/tmp_install/usr/bin:$PATH" python setup.py testr || echo "Tests failed"
 }
 
 package() {
diff --git a/community/tensorflow/PKGBUILD b/community/tensorflow/PKGBUILD
--- a/community/tensorflow/PKGBUILD
+++ b/community/tensorflow/PKGBUILD
@@ -5,35 +5,48 @@
 
 pkgbase=tensorflow
 pkgname=(tensorflow tensorflow-opt tensorflow-cuda tensorflow-opt-cuda python-tensorflow python-tensorflow-opt python-tensorflow-cuda python-tensorflow-opt-cuda)
-pkgver=2.3.1
-_pkgver=2.3.1
-pkgrel=2
+pkgver=2.5.0
+_pkgver=2.5.0
+pkgrel=4
 pkgdesc="Library for computation using data flow graphs for scalable machine learning"
 url="https://www.tensorflow.org/"
 license=('APACHE')
 arch=('loongarch64' 'x86_64')
 depends=('c-ares' 'intel-mkl' 'onednn' 'pybind11' 'openssl-1.0' 'lmdb' 'libpng' 'curl' 'giflib' 'icu' 'libjpeg-turbo')
-makedepends=('bazel' 'python-numpy' 'cuda' 'nvidia-utils' 'nccl' 'git' 'gcc9'
+makedepends=('bazel' 'python-numpy' 'cuda' 'nvidia-utils' 'nccl' 'git'
              'cudnn' 'python-pip' 'python-wheel' 'python-setuptools' 'python-h5py'
              'python-keras-applications' 'python-keras-preprocessing'
              'cython')
 optdepends=('tensorboard: Tensorflow visualization toolkit')
 source=("$pkgname-$pkgver.tar.gz::https://github.com/tensorflow/tensorflow/archive/v${_pkgver}.tar.gz"
-        https://github.com/tensorflow/tensorflow/commit/c6769e20bf6096d5828e2590def2b25edb3189d6.patch
-        numpy1.20.patch::https://github.com/tensorflow/tensorflow/commit/75ea0b31477d6ba9e990e296bbbd8ca4e7eebadf.patch
-        cuda11.1.patch
+        48935.patch
+        fix-c++17-compat.patch
         build-against-actual-mkl.patch)
-sha512sums=('e497ef4564f50abf9f918be4522cf702f4cf945cb1ebf83af1386ac4ddc7373b3ba70c7f803f8ca06faf2c6b5396e60b1e0e9b97bfbd667e733b08b6e6d70ef0'
-            '9dcaef0dd4fdd7008a27e383ef87c97990ba883a3094f214f821a039994933ec6ec47f5a832570e5c4b783e0493ce2236e7957e596395c4dee40f9bf2621ff2f'
-            'df2e0373e2f63b8766f31933f7db57f6a7559b8f03af1db51644fba87731451a7cd3895529a3192e5394612fcb42f245b794b1c9ca3c05881ca03a547c8c9acc'
-            '0caa5170c22fdea2c708ecdb2c980d668464d9dba9c9730a9ec5e9258572576d783fa1d19da04d5f9d2b06aed36d30971526f212fc64c53d09c3e821bd1a3b5d'
+sha512sums=('637c63b1bed1c0eb7bb018f1ff7f29f7f0d78e75dac384df4ecb5dfb92bbcb28209e3d3d2204145abddf88e3247d8c31bbb4cea032a73b7122b2ef3eb0d2b947'
+            '6dab3966de6e8065a3aa91575976df9593b56c7f347f5ef45cc791a4427b4569cde0b772ca6060f229d4e97ce637a69b04346a347c23cdc63420d8226da313ab'
+            'a39f4adff91a60b05c18c4c1ef99b65375887bbea5991610eb162a3c6e3562f8d4438f9f1e1910b672f6094235b5b70dea633578f7f6b5b931f221ca2805152a'
             'e51e3f3dced121db3a09fbdaefd33555536095584b72a5eb6f302fa6fa68ab56ea45e8a847ec90ff4ba076db312c06f91ff672e08e95263c658526582494ce08')
+
+# consolidate common dependencies to prevent mishaps
+_common_py_depends=(python-termcolor python-astor python-gast03 python-numpy python-protobuf absl-py python-h5py python-keras-applications python-keras-preprocessing python-tensorflow-estimator python-opt_einsum python-astunparse python-pasta python-flatbuffers)
 
 get_pyver () {
   python -c 'import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))'
 }
 
 check_dir() {
+  # first make sure we do not break parsepkgbuild
+  if ! command -v cp &> /dev/null; then
+    >&2 echo "'cp' command not found. PKGBUILD is probably being checked by parsepkgbuild."
+    if ! command -v install &> /dev/null; then
+      >&2 echo "'install' command also not found. PKGBUILD must be getting checked by parsepkgbuild."
+      >&2 echo "Cannot check if directory '${1}' exists. Ignoring."
+      >&2 echo "If you are not running nacmap or parsepkgbuild, please make sure the PATH is correct and try again."
+      >&2 echo "PATH should not be '/dummy': PATH=$PATH"
+      return 0
+    fi
+  fi
+  # if we are running normally, check the given path
   if [ -d "${1}" ]; then
     return 0
   else
@@ -49,15 +62,14 @@ prepare() {
   # Tensorflow actually wants to build against a slimmed down version of Intel MKL called MKLML
   # See https://github.com/intel/mkl-dnn/issues/102
   # MKLML version that Tensorflow wants to use is https://github.com/intel/mkl-dnn/releases/tag/v0.21
-  patch -Np1 -d tensorflow-${_pkgver} -i "$srcdir"/build-against-actual-mkl.patch
+  # patch -Np1 -d tensorflow-${_pkgver} -i "$srcdir"/build-against-actual-mkl.patch
 
-  # Fix wrong SONAME being shipped in CUDA 11.1
-  patch -Np1 -d tensorflow-${_pkgver} -i "$srcdir"/cuda11.1.patch
+  # https://github.com/tensorflow/tensorflow/pull/48935/files
+  patch -Np1 -d tensorflow-${_pkgver} -i "$srcdir"/48935.patch
 
-  # Compile with C++17 by default (FS#65953)
-  #sed -i "s/c++14/c++17/g" tensorflow-${_pkgver}/.bazelrc
-
-  patch -Np1 -d tensorflow-${_pkgver} -i "$srcdir"/numpy1.20.patch
+  # Get rid of hardcoded versions. Not like we ever cared about what upstream
+  # thinks about which versions should be used anyway. ;) (FS#68772)
+  sed -i -E "s/'([0-9a-z_-]+) .= [0-9].+[0-9]'/'\1'/" tensorflow-${_pkgver}/tensorflow/tools/pip_package/setup.py
 
   cp -r tensorflow-${_pkgver} tensorflow-${_pkgver}-opt
   cp -r tensorflow-${_pkgver} tensorflow-${_pkgver}-cuda
@@ -86,23 +98,25 @@ prepare() {
   export TF_SYSTEM_LIBS="boringssl,curl,cython,gif,icu,libjpeg_turbo,lmdb,nasm,pcre,png,pybind11,zlib"
   export TF_SET_ANDROID_WORKSPACE=0
   export TF_DOWNLOAD_CLANG=0
-  export TF_NCCL_VERSION=2.7
+  export TF_NCCL_VERSION=$(pkg-config nccl --modversion | grep -Po '\d+\.\d+')
   export TF_IGNORE_MAX_BAZEL_VERSION=1
   export TF_MKL_ROOT=/opt/intel/mkl
   export NCCL_INSTALL_PATH=/usr
-  export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-9
-  export HOST_C_COMPILER=/usr/bin/gcc-9
-  export HOST_CXX_COMPILER=/usr/bin/g++-9
+  export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-10
+  export HOST_C_COMPILER=/usr/bin/gcc-10
+  export HOST_CXX_COMPILER=/usr/bin/g++-10
   export TF_CUDA_CLANG=0  # Clang currently disabled because it's not compatible at the moment.
   export CLANG_CUDA_COMPILER_PATH=/usr/bin/clang
   export TF_CUDA_PATHS=/opt/cuda,/usr/lib,/usr
   export TF_CUDA_VERSION=$(/opt/cuda/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')
   export TF_CUDNN_VERSION=$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' /usr/include/cudnn_version.h)
-  export TF_CUDA_COMPUTE_CAPABILITIES=5.2,5.3,6.0,6.1,6.2,7.0,7.2,7.5,8.0,8.6
+  # https://github.com/tensorflow/tensorflow/blob/1ba2eb7b313c0c5001ee1683a3ec4fbae01105fd/third_party/gpus/cuda_configure.bzl#L411-L446
+  # according to the above, we should be specifying CUDA compute capabilities as 'sm_XX' or 'compute_XX' from now on
+  # add latest PTX for future compatibility
+  export TF_CUDA_COMPUTE_CAPABILITIES=sm_52,sm_53,sm_60,sm_61,sm_62,sm_70,sm_72,sm_75,sm_80,sm_86,compute_86
 
-  # Required until https://github.com/tensorflow/tensorflow/issues/39467 is fixed.
-  export CC=gcc-9
-  export CXX=g++-9
+  export CC=gcc-10
+  export CXX=g++-10
 
   export BAZEL_ARGS="--config=mkl -c opt --copt=-I/usr/include/openssl-1.0 --host_copt=-I/usr/include/openssl-1.0 --linkopt=-l:libssl.so.1.0.0 --linkopt=-l:libcrypto.so.1.0.0 --host_linkopt=-l:libssl.so.1.0.0 --host_linkopt=-l:libcrypto.so.1.0.0"
 }
@@ -156,7 +170,6 @@ build() {
   cd "${srcdir}"/tensorflow-${_pkgver}-opt-cuda
   export CC_OPT_FLAGS="-march=haswell -O3"
   export TF_NEED_CUDA=1
-  export TF_CUDA_CLANG=0
   ./configure
   bazel \
     build --config=avx2_linux \
@@ -185,6 +198,13 @@ _package() {
   rm -rf "${pkgdir}"/usr/bin
   rm -rf "${pkgdir}"/usr/lib
   rm -rf "${pkgdir}"/usr/share
+  # make sure no lib objects are outside valid paths
+  local _so_srch_path="${pkgdir}/usr/include"
+  check_dir "${_so_srch_path}"  # we need to quit on broken search paths
+  find "${_so_srch_path}" -type f,l \( -iname "*.so" -or -iname "*.so.*" \) -print0 | while read -rd $'\0' _so_file; do
+    # check if file is a dynamic executable
+    ldd "${_so_file}" &>/dev/null && rm -rf "${_so_file}"
+  done
 
   # install the rest of tensorflow
   tensorflow/c/generate-pc.sh --prefix=/usr --version=${pkgver}
@@ -202,6 +222,9 @@ _package() {
   ln -s libtensorflow_framework.so.${pkgver:0:1} "${pkgdir}"/usr/lib/libtensorflow_framework.so
   install -Dm644 tensorflow/c/c_api.h "${pkgdir}"/usr/include/tensorflow/tensorflow/c/c_api.h
   install -Dm644 LICENSE "${pkgdir}"/usr/share/licenses/${pkgname}/LICENSE
+
+  # Fix interoperability of C++14 and C++17. See https://bugs.archlinux.org/task/65953
+  patch -Np0 -i "${srcdir}"/fix-c++17-compat.patch -d "${pkgdir}"/usr/include/tensorflow/absl/base
 }
 
 _python_package() {
@@ -231,7 +254,7 @@ package_tensorflow() {
 }
 
 package_tensorflow-opt() {
-  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CPU optimizations)"
+  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with AVX2 CPU optimizations)"
   conflicts=(tensorflow)
   provides=(tensorflow)
 
@@ -250,7 +273,7 @@ package_tensorflow-cuda() {
 }
 
 package_tensorflow-opt-cuda() {
-  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CUDA and CPU optimizations)"
+  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CUDA and AVX2 CPU optimizations)"
   depends+=(cuda cudnn nccl)
   conflicts=(tensorflow)
   provides=(tensorflow tensorflow-cuda)
@@ -260,15 +283,15 @@ package_tensorflow-opt-cuda() {
 }
 
 package_python-tensorflow() {
-  depends+=(tensorflow python-termcolor python-astor python-gast python-numpy python-protobuf absl-py python-h5py python-keras-applications python-keras-preprocessing python-tensorflow-estimator python-opt_einsum python-astunparse python-pasta)
+  depends+=(tensorflow "${_common_py_depends[@]}")
 
   cd "${srcdir}"/tensorflow-${_pkgver}
   _python_package tmp
 }
 
 package_python-tensorflow-opt() {
-  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CPU optimizations)"
-  depends+=(tensorflow-opt python-termcolor python-astor python-gast python-numpy python-protobuf absl-py python-h5py python-keras-applications python-keras-preprocessing python-tensorflow-estimator python-opt_einsum python-astunparse python-pasta)
+  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with AVX2 CPU optimizations)"
+  depends+=(tensorflow-opt "${_common_py_depends[@]}")
   conflicts=(python-tensorflow)
   provides=(python-tensorflow)
 
@@ -278,7 +301,7 @@ package_python-tensorflow-opt() {
 
 package_python-tensorflow-cuda() {
   pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CUDA)"
-  depends+=(tensorflow-cuda python-termcolor python-astor python-gast python-numpy cuda cudnn python-pycuda python-protobuf absl-py nccl python-h5py python-keras-applications python-keras-preprocessing python-tensorflow-estimator python-opt_einsum python-astunparse python-pasta)
+  depends+=(tensorflow-cuda cuda cudnn nccl python-pycuda "${_common_py_depends[@]}")
   conflicts=(python-tensorflow)
   provides=(python-tensorflow)
 
@@ -287,8 +310,8 @@ package_python-tensorflow-cuda() {
 }
 
 package_python-tensorflow-opt-cuda() {
-  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CUDA and CPU optimizations)"
-  depends+=(tensorflow-opt-cuda python-termcolor python-astor python-gast python-numpy cuda cudnn python-pycuda python-protobuf absl-py nccl python-h5py python-keras-applications python-keras-preprocessing python-tensorflow-estimator python-opt_einsum python-astunparse python-pasta)
+  pkgdesc="Library for computation using data flow graphs for scalable machine learning (with CUDA and AVX2 CPU optimizations)"
+  depends+=(tensorflow-opt-cuda cuda cudnn nccl python-pycuda "${_common_py_depends[@]}")
   conflicts=(python-tensorflow)
   provides=(python-tensorflow python-tensorflow-cuda)
 
diff --git a/community/whipper/PKGBUILD b/community/whipper/PKGBUILD
--- a/community/whipper/PKGBUILD
+++ b/community/whipper/PKGBUILD
@@ -9,48 +9,56 @@
 # Contributor: Mantas Mikulėnas <grawity@gmail.com>
 
 pkgname=whipper
-pkgver=0.9.0
+pkgver=0.10.0
 pkgrel=1
 pkgdesc="A Unix CD ripper aiming for accuracy over speed -- forked from morituri"
 arch=('loongarch64' 'x86_64')
 url="https://github.com/whipper-team/whipper"
 license=('GPL3')
 depends=(
-  'cdrdao'                # for session, TOC, pregap, and ISRC extraction
-  'libcdio-paranoia'      # for the actual ripping
-  'libsndfile'            # for reading wav files (pulls in flac, also required for reading flac files)
-  'python-gobject'
-  'python-musicbrainzngs' # for metadata lookup
-  'python-mutagen'        # for metadata handling
-  'python-pycdio'         # for storing drive identification in config file
-  'python-requests'
-  'python-ruamel-yaml'    # for log output
-  'python-setuptools'     # for plugin support
-  'sox'                   # for track peak detection'
+  cdrdao                # for session, TOC, pregap, and ISRC extraction
+  libcdio-paranoia      # for the actual ripping
+  libsndfile            # for reading wav files (pulls in flac, also required for reading flac files)
+  python-gobject
+  python-musicbrainzngs # for metadata lookup
+  python-mutagen        # for metadata handling
+  python-pycdio         # for storing drive identification in config file
+  python-requests
+  python-ruamel-yaml    # for log output
+  python-setuptools     # for plugin support
+  sox                   # for track peak detection
 )
 checkdepends=(
-  'python-twisted'
+  python-twisted
 )
 optdepends=('flac: For free lossless audio codec (FLAC) support')
 makedepends=('python-setuptools-scm')
 conflicts=('accuraterip-checksum')
 provides=('accuraterip-checksum')
-source=("${url}/archive/v${pkgver}/${pkgname}-v${pkgver}.tar.gz")
-sha512sums=('49e66ad2c6e8450199a53a28bb71725704daac86ce2cbf68080d4dee1c2357cf8367ddb4735a07f2ffe612d84f016661e5b6f94efa9d5a7d6b8cf56ee32b0ae7')
+source=("${url}/archive/v${pkgver}/${pkgname}-v${pkgver}.tar.gz"
+        "c229c01a5821276de9ee275ccfebe99b51a1a8c8.patch")
+sha512sums=('728ad98185aa2d29f4fb215a597136691bb2c3590b3cac4f659238f90a3b4328c377fafe830a725b655f050538739f404b3eca853db4c39001d1b9d721dc7fd8'
+            '478cf26f36e77ad1fc9cb4f44995f807ce6b7c4810b426053a0439c5f7dab0dfbc32d027474a626af1911c58add1c9f295b41a4fb079dfed91b5c433a5d9da82')
+
+prepare() {
+  cd ${pkgname}-${pkgver}
+  patch -np1 < "${srcdir}/c229c01a5821276de9ee275ccfebe99b51a1a8c8.patch"
+}
 
 build() {
-  cd "${pkgname}-${pkgver}"
+  cd ${pkgname}-${pkgver}
   echo "Version: ${pkgver}" > PKG-INFO
   python setup.py build
 }
 
 check() {
-  cd "$srcdir/${pkgname}-${pkgver}"
+  cd ${pkgname}-${pkgver}
   local python_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
-  PYTHONPATH="build/lib.linux-${CARCH}-${python_version}/" python -m unittest discover
+  # https://github.com/whipper-team/whipper/issues/515
+  PYTHONPATH="build/lib.linux-${CARCH}-${python_version}/" python -m unittest discover || echo "Tests failed"
 }
 
 package() {
-  cd "$srcdir/${pkgname}-${pkgver}"
+  cd ${pkgname}-${pkgver}
   python setup.py install --root="${pkgdir}"/ --optimize=1 --skip-build
 }
